name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: NNBnh
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_timezone: Asia/Ho_Chi_Minh
          plugin_achievements: yes
          plugin_achievements_threshold: S
          plugin_chess: yes
          plugin_chess_platform: lichess.org
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_repositories: yes
          plugin_repositories_pinned: 6
